modules/pyramid/models/Node.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\models;

use app\helpers\Account;
use app\models\User;
use Exception;
use Yii;
use yii\db\ActiveRecord;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 * This is the model class for table "node".
 *
 * @property integer $id
 * @property string $user_name
 * @property integer $type_id
 * @property integer $count
 * @property integer $time
 *
 * @property Type $type
 * @property User $user
 * @property Node[] $children
 */
class Node extends ActiveRecord
{
    private $_children;

    public static function tableName() {
        return 'node';
    }

    public function rules() {
        return [
            [['user_name', 'type_id', 'count', 'time'], 'required'],
            [['type_id', 'count', 'time'], 'integer', 'min' => 0],
            [['user_name'], 'string', 'max' => 24],
            ['time', 'default', 'value' => $_SERVER['REQUEST_TIME']]
        ];
    }

    public function attributeLabels() {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_name' => Yii::t('app', 'Username'),
            'type_id' => Yii::t('app', 'Plan'),
            'count' => Yii::t('app', 'Counter'),
            'time' => Yii::t('app', 'Time'),
        ];
    }

    /**
     * @return User
     */
    public function getUser() {
        return $this->hasOne(User::class, ['name' => 'user_name']);
    }

    public function setUser(User $value) {
        $this->user_name = $value->name;
    }

    /**
     * @return Type
     */
    public function getType() {
        return $this->hasOne(Type::class, ['id' => 'type_id']);
    }

    public function setType(Type $value) {
        $this->type_id = $value->id;
    }

    public function getChildren() {
        if (!$this->_children) {
            $this->_children = Node::find()->where(['>', 'id', $this->id])->limit(40)->all();
        }
        return $this->_children;
    }

    public function countQueue() {
        return static::find()
            ->andWhere('time <= :time', [':time' => $this->time])
            ->andWhere(['type_id' => $this->type_id])
            ->sum('count');
    }

    public function decrement() {
        $this->count--;
        return $this->update(false, ['count']);
    }

    public function invest() {
        $this->count = $this->type->degree;
        $this->time = $_SERVER['REQUEST_TIME'];
        if ($expectant = $this->getExpectant($this->type_id)) {
            if ($expectant->count > 1) {
                $expectant->decrement();
            } else {
                $user = $expectant->user;
                $expectant->delete();

                Yii::$app->db->createCommand(
                    'INSERT INTO "income"(node_id,  user_name,  type_id, "time")
                          VALUES (:node_id, :user_name, :type_id, :time)', [
                    ':node_id' => $expectant->id,
                    ':user_name' => $expectant->user_name,
                    ':type_id' => $expectant->type_id,
                    ':time' => $expectant->time
                ])
                    ->execute();

                $user->account += (float)$this->type->income;
                if (!$user->update(false, ['account'])) {
                    throw new Exception($this->dump());
                }
            }
        }
        if ($this->save()) {
            Account::set('profit', $this->type->profit);
            return true;
        }
        return false;
    }

    /**
     * @param $type_id
     * @return Node
     */
    public static function getExpectant($type_id) {
        return static::find()->where(['type_id' => $type_id])->andWhere('count > 0')
            ->orderBy(['time' => SORT_ASC, 'id' => SORT_ASC])->limit(1)->one();
    }

    public function dump() {
        $bundle = [
            'id' => $this->id,
            'type_id' => $this->type_id,
            'count' => $this->count,
            'time' => date($this->time),
            'user_name' => $this->user_name,
            'account' => $this->user->account
        ];
        if (count($this->errors) > 0) {
            $bundle['errors'] = $this->errors;
        }
        if (count($this->user->errors) > 0) {
            $bundle['user_errors'] = $this->user->errors;
        }
        return json_encode($bundle, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    }

    public function __toString() {
        return $this->id . ' ' . Type::get($this->type_id);
    }
}

modules/pyramid/controllers/NodeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\controllers;


use app\behaviors\Access;
use app\modules\pyramid\models\Node;
use Yii;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class NodeController extends Controller
{
    public function behaviors() {
        return [
            'access' => [
                'class' => Access::class,
                'manager' => ['create', 'update', 'delete']
            ]
        ];
    }

    public function actionIndex($user = null, $id = null) {
        $parent = $id ? $this->findModel($id) : null;
        $query = Node::find()
            ->with('type')
            ->orderBy(['time' => SORT_ASC, 'id' => SORT_ASC]);
        if ($user) {
            $query->andWhere(['user_name' => $user]);
        }
        elseif ($parent) {
            $query
                ->andWhere('"time" < :time', [':time' => $parent->time])
                ->andWhere(['type_id' => $parent->type_id]);
        }
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => $query
            ]),
            'parent' => $parent
        ]);
    }

    public function actionCreate($id = null) {
        $model = new Node();
        if ($id) {
            $base = $this->findModel($id);
            $model->time = $base->time - 1;
            $model->type_id = $base->type_id;
        }
        else {
            $model->time = time();
        }

        $is_post = $model->load(Yii::$app->request->post());
        if ($is_post) {
            $model->count = $model->type->degree;
            if ($is_post && $model->validate()) {
                if ($model->save(false)) {
                    return $this->redirect(['invest', 'id' => $model->id]);
                }
            }
            else {
                Yii::$app->session->setFlash('error', json_encode($model->errors, JSON_UNESCAPED_UNICODE));
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['invest', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id) {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Type model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Node the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Node::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/pyramid/controllers/TypeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\modules\pyramid\controllers;


use app\modules\pyramid\models\Node;
use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\data\ActiveDataProvider;
use app\modules\pyramid\models\Type;
use yii\web\NotFoundHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class TypeController extends Controller {

    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'open' => ['post'],
                ]
            ]
        ];
    }

    public function actionIndex() {
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => Type::find(),
                'sort' => [
                    'defaultOrder' => ['id' => SORT_ASC]
                ]
            ]),
        ]);
    }

    public function actionView($id) {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionOpen($id) {
        $node = new Node([
            'type' => $this->findModel($id),
            'user' => Yii::$app->user->identity
        ]);

        if ($node->user->account >= $node->type->stake) {
            $node->user->account -= $node->type->stake;
            $transaction = Yii::$app->db->beginTransaction();
            try {
                if ($node->user->update(true, ['account']) && $node->invest()) {
                    $transaction->commit();
                    Yii::$app->session->setFlash('success', Yii::t('app', 'The plan is open'));
                }
            }
            catch(\Exception $ex) {
                $transaction->rollBack();
                Yii::$app->session->setFlash('error', $ex->getMessage());
            }
        }
        else {
            Yii::$app->session->setFlash('error', Yii::t('app', 'Insufficient funds'));
            return $this->redirect(['view', 'id' => $node->id]);
        }

        return $this->redirect(['view', 'id' => $id]);
    }

    /**
     * Finds the Type model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Type the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Type::get($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/pyramid/views/node/_form.php
<?php
/**
 * @link http://zenothing.com/
*/

use app\models\Type;
use app\widgets\AjaxComplete;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Node */
/* @var $form yii\widgets\ActiveForm */

$types = Type::getItems();
?>

<div class="type-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'user_name')->widget(AjaxComplete::class, [
        'route' => ['user/complete']
    ]) ?>
    <?= $form->field($model, 'type_id')->dropDownList($types) ?>
    <?php
    if (!$model->isNewRecord) {
        echo $form->field($model, 'count');
    }
    ?>
    <?php
    array_unshift($types, Yii::t('app', 'Investment'), 0);
    unset($types[1]);
    echo $form->field($model, 'reinvest_from')->dropDownList($types);
    echo Html::activeHiddenInput($model, 'time');
    ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord
            ? Yii::t('app', 'Create')
            : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/pyramid/views/node/create.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Type */

$this->title = Yii::t('app', 'Create Investment');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Queue'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="type-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/pyramid/views/node/index.php
<?php
/**
 * @link http://zenothing.com/
 */

use app\modules\pyramid\models\Node;
use app\widgets\Ext;
use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View
 * @var $parent Node
 * @var $dataProvider yii\data\ActiveDataProvider
 */

$user = isset($_GET['user']) ? $_GET['user'] : null;
$mine = !Yii::$app->user->isGuest && (Yii::$app->user->identity->isManager() || Yii::$app->user->identity->name == $user);
$title = $this->title = Yii::t('app', 'Investments');
$columns = [
    'id',
    [
        'attribute' => 'user_name',
        'format' => 'html',
        'value' => function($model) {
            return Html::a($model->user_name, ['user/view', 'name' => $model->user_name]);
        }
    ],
    'time:datetime',
    [
        'label' => Yii::t('app', 'Action'),
        'format' => 'html',
        'value' => function($model) {
            return Html::a(Yii::t('app', 'View'), ['index', 'id' => $model->id],
                ['class' => 'btn btn-primary btn-xs']);
        }
    ]
];


if (isset($parent)) {
    $title = $parent->type->name . " #$parent->id ";
    $this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Investments'), 'url' => ['index']];
    $this->params['breadcrumbs'][] = $title;
    $this->title = $title;
    $title .= $mine ? Html::a($parent->user_name, ['user/view', 'name' => $parent->user_name]) : $parent->user_name;

}
else {
    $additional = [$columns[0],
        [
            'attribute' => 'type_id',
            'label' => Yii::t('app', 'Plan'),
            'format' => 'html',
            'value' => function($model) {
                return Html::a($model->type->name, ['type/view', 'id' => $model->type_id]);
            }
        ]
    ];
    if ($user) {
        $this->title = Yii::t('app', 'Investments of user') . ' ' . $user;
        if ($mine) {
            $title = Yii::t('app', 'Investments of user') . ' ' . Html::a($user, ['user/view', 'name' => $user]);
        }
        else {
            $title = $this->title;
        }
        $additional[] = [
            'attribute' => 'time',
            'label' => Yii::t('app', 'Remains to exit'),
            'value' => function(Node $model) {
                return $model->countQueue();
            }

        ];
    }
    $columns = array_merge($additional, array_slice($columns, 1));
}

?>
<div class="invest">
    <?= Ext::stamp() ?>
    <div>
        <h1><?= $title ?></h1>

        <div class="form-group">
            <?php
            if (empty($parent)) {
                echo Html::a(Yii::t('app', 'Open'), ['plan'], ['class' => 'btn btn-success']);
            }
            else {
                if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
                    echo implode(' ', [
                        Html::a(Yii::t('app', 'Update'), ['update', 'id' => $parent->id], ['class' => 'btn btn-primary']),
                        Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $parent->id], ['class' => 'btn btn-danger']),
                        Html::a(Yii::t('app', 'Up'), ['up', 'id' => $parent->id], ['class' => 'btn btn-warning'])
                    ]);
                }
            }
            ?>
        </div>

        <?php
        if (isset($parent)) {
            echo Html::tag('p', Yii::t('app', 'Remains to exit') . ': ' . $parent->countQueue());
        }
        ?>
    </div>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'summary' => '',
        'emptyText' => '',
        'showOnEmpty' => false,
        'columns' => $columns,
    ])
    ?>

</div>

modules/pyramid/views/node/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Type */

$this->title = Yii::t('app', 'Update');
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['invest', 'id' => $model->id]];
$this->params['breadcrumbs'][] = Yii::t('app', 'Update');
?>
<div class="type-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/pyramid/views/node/view.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Node */

$this->title = $model->type->name . " #$model->id";
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Queue'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'Investment'), 'url' => ['invest']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="type-view">

    <h1 class="bagatelle"><?= Html::encode($this->title) ?></h1>

    <div id="matrix">
        <h2><?= count($model->children) ?> из <?= $model->type->degree ?></h2>
        <?php
        foreach($model->children as $child) {
            echo Html::a($child->user_name, ['user/view', 'name' => $child->user_name]);
        }
        ?>
    </div>
</div>